version: 2

sources:
  - name: fec
    database: raw
    schema: fec
    tables:
      - name: cm
        columns:
          - name: cmte_id
            tests:
              - unique
      - name: cn
        columns:
          - name: cand_id
            tests:
              - unique
      - name: oppexp
        columns:
          - name: sub_id
            tests:
              - unique
      - name: itcont
        columns:
          - name: sub_id
            tests:
              - unique
      - name: dates
        columns:
          - name: datekey
            tests:
              - unique
      - name: reporttypes
        columns:
          - name: reporttypecode
            tests:
              - unique
      - name: expensecategories
        columns:
          - name: expensecategorycode
            tests:
              - unique
      - name: zipcodes
        columns:
          - name: zipcode
            tests:
              - unique
      - name: amendmenttypes
        columns:
          - name: amendmenttypecode
            tests:
              - unique
      - name: transactiontypes
        columns:
          - name: transactiontypecode
            tests:
              - unique
      - name: entitytypes
        columns:
          - name: entitytypecode
            tests:
              - unique
